### ISSUE TITLE
Not working with 2019.3

### ISSUE THREAD

**Issue by CenekStrichel** [KartikShrivastava/unity-screen-recorder-krtk#2]
Hello, it looks like a great plugin. But it is not working with current Unity. Do you plan some update?

`
2020.05.18 03:18:55.622 3932 3979 Error MediaRecorder start called in an invalid state: 32
2020.05.18 03:18:55.739 3932 3979 Error Unity AndroidJavaException: java.lang.IllegalStateException
2020.05.18 03:18:55.739 3932 3979 Error Unity java.lang.IllegalStateException
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at android.media.MediaRecorder.start(Native Method)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at com.techgeekfreax.screenrecorder.screenrecorderlib.AndroidUtils.startRecording(AndroidUtils.java:134)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:103)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at android.os.Looper.loop(Looper.java:214)
2020.05.18 03:18:55.739 3932 3979 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2020.05.18 03:18:55.739 3932 3979 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00096] in <3c22a197ab60454cb70124c69f2248be>:0 
2020.05.18 03:18:55.739 3932 3979 Error Unity   at UnityEngine.AndroidJNISafe.CallVoidMethod (System.IntPtr obj, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x0000f] in <3c22a197ab60454cb70124c69f2248be>:0 
2020.05.18 03:18:55.739 3932 3979 Error Unity   at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00038] in <3c22a197ab60454cb70124c69f2248be>:0 
2020.05.18 03:18:55.739 3932 3979 Error Unity   at Un
`

**Comment by ark-tik** [comment]
Hi @CenekStrichel , 
I've just built the plugin with Unity2019.2 and it's working fine for me. I guess that your issue is related with your jdk configuration, also make sure to use API level higher than 21 while building the plugin in any android device.
As of now plugin is saving the recorded videos in a folder named ```Pikamoji_Moments``` you can change it from ```convertToAAC``` method in ```AndroidUtils.java``` class of android studio project (need to compile .aar file again).
